typos:
- ", that"
- "smart phone"
- "Smart phone"
- "signalling"
- "Signalling"
- "optimis"
- "Optimis"
- " \\cite"
- "tradeoff"
- "trade off"
- "power consumption"
- "such as "
- "three state "
- "two state "
- "because"
- " he "
- " his "
- " she "
- "analysed"
- "parameterised"
- "usecase"
- "internet"
- "utilisation"
- "plattform"
- "centre"
- "virtualised"
- "Virtualisation"
- "pareto"
- "tree like"
- "client based"
- "decreASs"
- "ISP-cache"
- "analyse"
- "server group"
- "have seen"
